# chart-repo: stable/cluster-autoscaler
# chart-version: 0.12.1
# chart-node: master

nameOverride: cluster-autoscaler

# podAnnotations:
#   cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

image:
  repository: K8SGCR/cluster-autoscaler

autoDiscovery:
  enabled: true
  clusterName: CLUSTER_NAME

awsRegion: AWS_REGION

extraArgs:
  v: 4
  stderrthreshold: info
  logtostderr: true
  expander: random
  scale-down-enabled: true
  scale-down-utilization-threshold: 0.75
  skip-nodes-with-local-storage: false
  skip-nodes-with-system-pods: false

#:MASTER:nodeSelector:
#:MASTER:  kubernetes.io/role: master

#:MASTER:tolerations:
#:MASTER:  - effect: NoSchedule
#:MASTER:    key: node-role.kubernetes.io/master

sslCertPath: /etc/ssl/certs/ca-bundle.crt

rbac:
  create: true
  pspEnabled: true
