# chart-repo: stable/cluster-autoscaler
# chart-version: 6.5.0
# chart-node: master

nameOverride: cluster-autoscaler

# podAnnotations:
#   cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

image:
  repository: K8SGCR/cluster-autoscaler
  tag: v1.14.6

## Only cloudProvider `aws` and `gce` are supported by auto-discovery at this time
## AWS: Set tags as described in https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup
autoDiscovery:
  enabled: true
  clusterName: CLUSTER_NAME

## Currently only gce, aws, azure spotinst are supported
cloudProvider: aws
awsRegion: AWS_REGION

extraArgs:
  v: 4
  stderrthreshold: info
  logtostderr: true
  expander: random
  scale-down-enabled: true
  scale-down-utilization-threshold: 0.75
  skip-nodes-with-local-storage: false
  skip-nodes-with-system-pods: false

#:MASTER:nodeSelector:
#:MASTER:  kubernetes.io/role: master

#:MASTER:tolerations:
#:MASTER:  - effect: NoSchedule
#:MASTER:    key: node-role.kubernetes.io/master

sslCertPath: /etc/ssl/certs/ca-bundle.crt

rbac:
  ## If true, create & use RBAC resources
  create: true
  ## If true, create & use Pod Security Policy resources
  ## https://kubernetes.io/docs/concepts/policy/pod-security-policy/
  pspEnabled: true
