# chart-repo: stable/efs-provisioner
# chart-version: 0.11.0
# chart-pdb: N 1

nameOverride: efs-provisioner

# podAnnotations:
#   cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

image:
  repository: QUAY/external_storage/efs-provisioner
  tag: v2.4.0

busyboxImage:
  repository: GCR/google_containers/busybox
  tag: 1.27

## https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs#deployment
efsProvisioner:
  #EFS_CHART_CHINA_DNS
  #EFS_CHART_EFSID
  #EFS_CHART_REGION
  path: /shared
  provisionerName: CLUSTER_NAME/efs
  storageClass:
    name: efs
    isDefault: false
    gidAllocate:
      enabled: true
      gidMin: 40000
      gidMax: 50000
    reclaimPolicy: Retain
