#
# CircleCI 2.0
#
version: 2
jobs:
  package:
    docker:
      - image: circleci/python
    working_directory: ~/works
    steps:
      - checkout
      - run:
          name: Package
          command: |
            mkdir target
            cp ./builder.sh target/builder.sh
            bash ./target/builder.sh package
      - persist_to_workspace:
          root: ~/works
          paths:
            - target
  release:
    docker:
      - image: circleci/golang
    working_directory: ~/works
    steps:
      - attach_workspace:
          at: ~/works
      - run:
          name: Release
          command: |
            bash ./target/builder.sh release
  slack:
    docker:
      - image: circleci/python
    working_directory: ~/works
    steps:
      - attach_workspace:
          at: ~/works
      - run:
          name: Slack
          command: |
            bash ./target/builder.sh slack

workflows:
  version: 2
  apply:
    jobs:
      - package
      - release:
          requires:
            - package
      - slack:
          requires:
            - release
