# chart-repo: kiwigrid/fluentd-elasticsearch
# chart-version: 8.0.0

## https://github.com/kiwigrid/helm-charts/tree/master/charts/fluentd-elasticsearch

nameOverride: fluentd-elasticsearch

image:
  repository: quay.io/fluentd_elasticsearch/fluentd

## If using AWS Elasticsearch, all requests to ES need to be signed regardless of whether
## one is using Cognito or not. By setting this to true, this chart will install a sidecar
## proxy that takes care of signing all requests being sent to the AWS ES Domain.
awsSigningSidecar:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi
  network:
    port: 8080
    address: localhost
    remoteReadTimeoutSeconds: 15
  image:
    repository: abutaha/aws-es-proxy

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  limits:
    cpu: 100m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 200Mi

elasticsearch:
  bufferChunkLimit: "8M"
  bufferQueueLimit: 8
  hosts: ["CUSTOM_HOST:CUSTOM_PORT"]
  logstashPrefix: "logstash"
  path: ""
  scheme: "https"
  sslVerify: true
  sslVersion: "TLSv1_2"
  outputType: "elasticsearch"
  typeName: "_doc"
  logLevel: "info"

configMaps:
  useDefaults:
    systemConf: true
    containersInputConf: true
    systemInputConf: true
    forwardInputConf: true
    monitoringConf: true
    outputConf: true
    
